### ISSUE TITLE
Error restoring to new Integrator Free Plan account

### ISSUE THREAD

**Issue by toomasaas** [edunham/envsync#6]
Hello!

I'm trying to migrate from my current developer account to new Integrator Free Plan account. I could successfully make a backup using 'envsync backup', but trying to restore to my new Integrator Free Plan instance results in an error:

```
$ envsync restore -i backup/dev-13488660 2>&1 | tee restore.log
Using configuration from /home/toomas/.okta/okta.yaml
Error: this tool is only designed for Okta developer accounts (dev-*.okta)

```

The URL of my Integrator Free Plan account is https://trial-6278067.okta.com and I have specified it in my $HOME/.okta/okta.yaml file.

**Comment by edwinszhang** [comment]
Same error. 
```
okta:
  client:
    connectionTimeout: 30 # seconds
    orgUrl: "https://{yourOktaDomain}"
    proxy:
      port: null
      host: null
      username: null
      password: null
    token: {apiToken}
```

Followed this structure as my restore yaml file when I tried to restore to new Integrator Free Plan account. 
I thought replace  trail-* domain to {yourOktaDomain} can restore the data and it got same error.
